### ISSUE TITLE
Ortografía!!!

### ISSUE THREAD

**Issue by kcifuentes** [Laraveles/lang-spanish#13]
Hola, espero no incomodar, solo quiero hacerles la observación ortográfica siguiente, para que lo tengan en cuenta.

No es Reestablecer, es Restablecer.
No es Reestablecido, es Restablecido.
No es Reestablecimiento, es Restablecimiento.

Solo es eso, aunque es algo muy sencillo de modificar, es solo para que lo tengan en cuenta.

**Comment by luvejo** [comment]
Hola, @kcifuentes. En cuanto a correcciones ortográficas, la incomodidad sería con el usuario final. ¡Gracias por el aporte!

**Comment by IsraelOrtuno** [comment]
Creo que ya se incluyó con ese PR

**Comment by luvejo** [comment]
Sí, ahí vamos aprendiendo. :boat:
